### ISSUE TITLE
Upgrade packages/klingon-ui to CLI v6

### ISSUE THREAD

**Issue by manekinekko** [angular-klingon/klingon#25]
The packages/klingon-ui package needs to be upgraded to the latest Angular CLI.

**Comment by sumitparakh** [comment]
Upgraded.

 #32

**Comment by manekinekko** [comment]
Hi, thank you for fixing this issue !
Your PR is now in conflict. Could you please update it? thanks

**Comment by sumitparakh** [comment]
Hi @manekinekko . It is updated now.  Please check.

**Comment by manekinekko** [comment]
Merge.
