### ISSUE TITLE
Server: NPM install fails due node-pty problem during lerna bootstrap execution

### ISSUE THREAD

**Issue by ialex90** [angular-klingon/klingon#34]
When you run npm install to fetch all the packages, there is a postscript after installation (postinstall) to bootstrap by lerna that it fails in version 10 of node.

Current versions:
- npm: 6.2.0
- node: 10.7.0

The problem actually resides in a dependency version of node-pty.
There is a fix in the release log of node-pty. [This was merged in version 0.7.5.](https://github.com/Microsoft/node-pty/releases/tag/0.7.5)

More info:
_issue_: https://github.com/Microsoft/node-pty/issues/192
_commit_: https://github.com/Microsoft/node-pty/commit/79b5b0cccf3db3f0eb2f9f73d8ec964ab49a6bf6

**Comment by manekinekko** [comment]
does #35 fix this issue?

**Comment by ialex90** [comment]
yes
