### ISSUE TITLE
switch to angular/master#HEAD

### ISSUE THREAD

**Issue by manekinekko** [angular-klingon/klingon#55]
Let's use angular#master^HEAD as our main version.

NOTE: this is forcing us to stay up to date but also, this may introduce some breaking changes, so we should be reactive and fix bugs as they arise ^^

**Comment by daniloff200** [comment]
As far, as I understood,  needed changes should be done in https://github.com/angular-klingon/klingon/blob/master/packages/klingon-ui/package.json , right?

If so, I could take it, after finishing the same task in xlayers repo

**Comment by manekinekko** [comment]
We are gonna drop this for now.

**Comment by manekinekko** [comment]
@sumitparakh you can close this one.
