### ISSUE TITLE
Prepopulate the Project Root directory field with a 'default' value

### ISSUE THREAD

**Issue by manekinekko** [angular-klingon/klingon#82]
**Describe the solution you'd like**
We could prepopulate the Project Root directory field in the UI with the current directory allocated to the server (ie, process.cwd()), another value (maybe from config?).

This can prevent issue #81 

@sumitparakh what do you think?

**Comment by sumitparakh** [comment]
> **Describe the solution you'd like**
> We could prepopulate the Project Root directory field in the UI with the current directory allocated to the server (ie, process.cwd()), another value (maybe from config?).
> 
> This can prevent issue #81
> 
> @sumitparakh what do you think?

prepopulating from current directory(default) is a good idea. I think populating a filesystem path from config would not be OS independent. What do you think?
